### ISSUE TITLE
Add pipenv command to the other notebook

### ISSUE THREAD

**Issue by PaulineMCraft** [craft-ai/craft-ai-starterkit-jupyter#7]
Indicate the pipenv command to launch the other notebook (eg: notebook benchmark)

**Comment by PierreSalaun** [comment]
@PaulineMCraft benchmark is now using poetry instead of pipenv.
I haven't found any other occurrences of project using pipenv without the command to launch jupyter notebook.
Are there any other changes that are expected?

**Comment by PierreSalaun** [comment]
The goal of the starterkit being giving code examples that users can edit and reuse, the scripts executing notebooks are not relevant.

**Comment by PierreSalaun** [comment]
Those scripts are use for CI tests, so let's just leave them where they are.
Closing this issue.
